{
 "title": "Carbon Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Carbon Level in Region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "carbon_intensity_gco2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pods per Region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\n  sum by (namespace) (kube_pod_status_phase{namespace=~\"region-.*\", phase=\"Running\", pod=~\"sim-.*\"}),\n  \"namespace\", \"$1\", \"namespace\", \"(.*)\"\n)\nor \nlabel_replace(vector(0), \"namespace\", \"region-eu-west\", \"\", \"\")\nor \nlabel_replace(vector(0), \"namespace\", \"region-us-east\", \"\", \"\")\nor \nlabel_replace(vector(0), \"namespace\", \"region-asia-east\", \"\", \"\")",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Sum of Emissions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "# EUROPE PART\n(\n  (\n    (sum(kube_pod_status_phase{namespace=\"region-eu-west\", phase=\"Running\", pod=~\"sim-app-.*\"}) or vector(0)) * 0.20 +\n    (sum(kube_pod_status_phase{namespace=\"region-eu-west\", phase=\"Running\", pod=~\"sim-job-.*\"}) or vector(0)) * 0.15 +\n    (sum(kube_pod_status_phase{namespace=\"region-eu-west\", phase=\"Running\", pod=~\"sim-burst-.*\"}) or vector(0)) * 0.30\n  )\n  * scalar(sum(carbon_intensity_gco2{region=\"region-eu-west\"}) or vector(0))\n)\n+\n# USA PART\n(\n  (\n    (sum(kube_pod_status_phase{namespace=\"region-us-east\", phase=\"Running\", pod=~\"sim-app-.*\"}) or vector(0)) * 0.20 +\n    (sum(kube_pod_status_phase{namespace=\"region-us-east\", phase=\"Running\", pod=~\"sim-job-.*\"}) or vector(0)) * 0.15 +\n    (sum(kube_pod_status_phase{namespace=\"region-us-east\", phase=\"Running\", pod=~\"sim-burst-.*\"}) or vector(0)) * 0.30\n  )\n  * scalar(sum(carbon_intensity_gco2{region=\"region-us-east\"}) or vector(0))\n)\n+\n# ASIA PART\n(\n  (\n    (sum(kube_pod_status_phase{namespace=\"region-asia-east\", phase=\"Running\", pod=~\"sim-app-.*\"}) or vector(0)) * 0.20 +\n    (sum(kube_pod_status_phase{namespace=\"region-asia-east\", phase=\"Running\", pod=~\"sim-job-.*\"}) or vector(0)) * 0.15 +\n    (sum(kube_pod_status_phase{namespace=\"region-asia-east\", phase=\"Running\", pod=~\"sim-burst-.*\"}) or vector(0)) * 0.30\n  )\n  * scalar(sum(carbon_intensity_gco2{region=\"region-asia-east\"}) or vector(0))\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}